version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - webnet
  api:
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    container_name: postgres
    networks:
      - webnet
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: