version: '3.7'
services:
  nodeserver:
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - /etc/letsencrypt/:/etc/letsencrypt/