version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api
    networks:
      - webnet
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ --force-renewal --email ceo@thespecialcharacter.com -d api.scottpoint.com.au --agree-tos
  api:
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env.prod
    networks:
      - webnet
networks:
  webnet:
