version: '3.7'

services:
  api:
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env.prod
    networks:
      - webnet
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      # - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
      # - ./certbot/conf:/etc/letsencrypt
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./public_html:/public_html
      # - ./conf.d:/etc/nginx/conf.d/
      # - ./dhparam:/etc/nginx/dhparam
      # - ./certbot/conf/:/etc/nginx/ssl/
      # - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - api
    networks:
      - webnet
  certbot:
    # image: certbot/certbot:latest
    # volumes:
    #    - ./certbot/conf/:/etc/letsencrypt
    #    - ./certbot/logs/:/var/log/letsencrypt
    #    - ./certbot/data:/usr/share/nginx/html/letsencrypt
    # image: certbot/certbot:latest
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
        - ./.env.prod
    # volumes:
    #   - ./certbot/www/:/var/www/certbot/:rw
    #   - ./certbot/conf/:/etc/letsencrypt/:rw
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
      # - ./certbot/conf/:/etc/letsencrypt/:rw
    # command: certonly --webroot -w /var/www/certbot/ --force-renewal --email ceo@thespecialcharacter.com -d api.scottpoint.com.au --agree-tos
    # command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email ceo@thespecialcharacter.com --agree-tos --no-eff-email -d api.scottpoint.com.au
    depends_on:
      - nginx
    networks:
      - webnet
networks:
  webnet:

volumes:
  # xvar/run/docker.sock:
  certs:
  html:
  vhost:
  acme: